# Site settings
title: "Aurélien's personal website"
description: "aureooms website"
url: "https://aureooms.github.io"
author:
  name: "Aurélien Ooms"
  email: "aurelien.ooms@riseup.net"
  url: "https://aureooms.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
include: [./keybase.txt,./.ssh/id_rsa.pub]
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: true
reverse: false

# Gems
gems: [jekyll-paginate]
